/**
 * REF: Todo Creation Form Component
 *
 * Form component for creating new todos with title, description, public visibility, and tags.
 * Handles validation, error states, and insertion into Supabase PostgreSQL.
 *
 * CLOSE: Import and use in parent components (Dashboard, etc.) to allow users to create todos.
 * Passes userId prop and optional onSuccess callback.
 *
 * ### Props
 * | `Prop` | Type | `Required` | Purpose |
 * |------|------|----------|---------|
 * | `userId` | `string` | `Yes` | Supabase user ID for RLS enforcement |
 * | `onSuccess` | `function` | `No` | Callback after successful creation |
 *
 * FORM FIELDS:
 * | `Field` | Type | `Required` | Max Length | Purpose |
 * |-------|------|----------|-----------|---------|
 * | `title` | `text` | `Yes` | `-` | Main task text |
 * | `description` | `textarea` | `No` | `-` | Optional details |
 * | `isPublic` | `checkbox` | `No` | `-` | Make todo visible to others |
 * | `tags` | `array` | `No` | `10` | Searchable/filterable tags |
 *
 * STATE MANAGEMENT:
 * ```typescript
 * title: string              // Form input state
 * description: string        // Form input state
 * isPublic: boolean          // Checkbox state
 * tags: string[]             // Array of tag strings
 * tagInput: string           // Input field for new tag
 * loading: boolean           // Submission in progress
 * error: string              // Error message if submission fails
 * ```
 *
 * SUBMISSION FLOW:
 * 1. User fills form and clicks "Create Todo"
 * 2. handleSubmit validates title (required)
 * 3. Sets loading=true, clears error
 * 4. Calls supabase.from('todos').insert({...})
 * 5. RLS policy validates user_id = auth.uid()
 * 6. If success, clears form and calls onSuccess callback
 * 7. If error, displays message and keeps form data
 *
 * TAG MANAGEMENT:
 * - Add tag: User types tag name and clicks "Add" or presses Enter
 * - Validation: No duplicates, max 10 tags, trim whitespace
 * - Remove tag: Click × button on tag chip
 * - Display: Hashtag-prefixed blue chips
 *
 * ## Error Handling
 * | `Scenario` | Error Message |
 * |----------|---------------|
 * | Empty title | "Title is required" |
 * | RLS violation | "new row violates row-level security policy" |
 * | Database error | Server error message |
 *
 * TECHNICAL DETAILS:
 * - Uses Supabase JS client for INSERT operation
 * - .select().single() returns inserted row
 * - Null coalescing for optional fields
 * - RLS ensures user_id matches JWT token owner
 * - Timestamps auto-generated by PostgreSQL triggers
 *
 * SUPABASE QUERY PATTERN:
 * ```typescript
 * const { data, error } = await supabase
 *   .from('todos')
 *   .insert({
 *     user_id: userId,
 *     title: title.trim(),
 *     description: description.trim() || null,
 *     is_public: isPublic,
 *     tags: tags.length > 0 ? tags : null,
 *     completed: false
 *   })
 *   .select()
 *   .single()
 * ```
 */

import { useState, FormEvent } from 'react'
import { supabase } from '../lib/supabase'

interface TodoFormProps {
  userId: string
  onSuccess?: () => void
}

export default function TodoForm({ userId, onSuccess }: TodoFormProps) {
  const [title, setTitle] = useState('')
  const [description, setDescription] = useState('')
  const [isPublic, setIsPublic] = useState(false)
  const [tags, setTags] = useState<string[]>([])
  const [tagInput, setTagInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  /**
   * SUBMIT HANDLER
   *
   * Inserts into PostgreSQL via Supabase client
   *
   * RLS ENFORCEMENT:
   * - Policy checks user_id = auth.uid()
   * - Even if we try to set different user_id, database blocks it
   * - Security at the source!
   */
  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault()
    setError('')

    if (!title.trim()) {
      setError('Title is required')
      return
    }

    setLoading(true)

    try {
      const { data, error: insertError } = await supabase
        .from('todos')
        .insert({
          user_id: userId,
          title: title.trim(),
          description: description.trim() || null,
          is_public: isPublic,
          tags: tags.length > 0 ? tags : null,
          completed: false,
        })
        .select()
        .single()

      if (insertError) throw insertError

      // Clear form
      setTitle('')
      setDescription('')
      setIsPublic(false)
      setTags([])

      onSuccess?.()
    } catch (err: any) {
      console.error('Error:', err)
      setError(err.message || 'Failed to create todo')
    } finally {
      setLoading(false)
    }
  }

  const handleAddTag = () => {
    const tag = tagInput.trim().toLowerCase()
    if (tag && !tags.includes(tag) && tags.length < 10) {
      setTags([...tags, tag])
      setTagInput('')
    }
  }

  const handleRemoveTag = (tag: string) => {
    setTags(tags.filter(t => t !== tag))
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {error && (
        <div className="bg-red-100 text-red-700 px-4 py-3 rounded">
          {error}
        </div>
      )}

      <div>
        <label htmlFor="title" className="block text-sm font-medium mb-2">
          Title <span className="text-red-500">*</span>
        </label>
        <input
          id="title"
          type="text"
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          required
          className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
          placeholder="What needs to be done?"
        />
      </div>

      {/** REF: description-textarea
       * Multi-line description textarea field.
       * Provides 3 rows for detailed todo descriptions.
       */}
      <div>
        <label htmlFor="description" className="block text-sm font-medium mb-2">
          Description
        </label>
        <textarea
          id="description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          rows={3}
          className="w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500"
          placeholder="Add details..."
        />
      </div>
      {/* CLOSE: description-textarea */}

      {/** REF: public-checkbox
       * Checkbox to mark todo as public or private.
       * Toggles isPublic state when changed.
       */}
      <div className="flex items-center gap-2">
        <input
          id="isPublic"
          type="checkbox"
          checked={isPublic}
          onChange={(e) => setIsPublic(e.target.checked)}
          className="w-4 h-4"
        />
        <label htmlFor="isPublic" className="text-sm cursor-pointer">
          Make public
        </label>
      </div>
      {/* CLOSE: public-checkbox */}

      {/** REF: tags-section
       * Tags input section allowing users to add and manage tags.
       * Features tag input with Enter key support and add button.
       */}
      {/* Tags */}
      <div>
        <label className="block text-sm font-medium mb-2">Tags</label>
        <div className="flex gap-2 mb-2">
          <input
            type="text"
            value={tagInput}
            onChange={(e) => setTagInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && (e.preventDefault(), handleAddTag())}
            className="flex-1 px-4 py-2 border rounded-lg"
            placeholder="Add tag..."
          />
          <button
            type="button"
            onClick={handleAddTag}
            className="px-4 py-2 bg-gray-200 rounded hover:bg-gray-300"
          >
            Add
          </button>
        </div>

        {tags.length > 0 && (
          <div className="flex flex-wrap gap-2">
            {tags.map(tag => (
              <span key={tag} className="inline-flex items-center gap-1 px-3 py-1 bg-blue-100 rounded-full text-sm">
                #{tag}
                <button type="button" onClick={() => handleRemoveTag(tag)}>×</button>
              </span>
            ))}
          </div>
        )}
      </div>
      {/* CLOSE: tags-section */}

            <button
        type="submit"
        disabled={loading}
        className="w-full py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-gray-400"
      >
        {loading ? 'Creating...' : 'Create Todo'}
      </button>
    </form>
  )
}

/**
 * POSTGRESQL ARRAY ADVANTAGES
 *
 * Query with array operators:
 * ```typescript
 * // Contains specific tag
 * const { data } = await supabase
 *   .from('todos')
 *   .select('*')
 *   .contains('tags', ['urgent'])
 *
 * // Overlaps with tags
 * const { data } = await supabase
 *   .from('todos')
 *   .select('*')
 *   .overlaps('tags', ['work', 'urgent'])
 * ```
 *
 * Create GIN index for fast searches:
 * ```sql
 * CREATE INDEX idx_todos_tags ON todos USING GIN(tags);
 * ```
 */

/**
 * TYPE GENERATION
 *
 * Generate types from database:
 * ```bash
 * npx supabase gen types typescript --project-id YOUR_ID > src/lib/database.types.ts
 * ```
 *
 * Then import:
 * ```typescript
 * import type { Database } from '../lib/database.types'
 *
 * type Todo = Database['public']['Tables']['todos']['Row']
 * type NewTodo = Database['public']['Tables']['todos']['Insert']
 * ```
 *
 * Full autocomplete for all database operations!
 */

/**
 * REF: form-submission-handler
 *
 * ## Form Submission & Validation
 *
 * ### Client-Side Validation
 * - Title required and non-empty (trimmed)
 * - Max length enforced by HTML maxLength attribute
 * - Tags limited to 10 maximum
 * - Description optional but trimmed
 *
 * ### Supabase Insert Operation
 * ```typescript
 * const { data, error } = await supabase
 *   .from('todos')
 *   .insert({
 *     user_id,           // From auth
 *     title,             // Required
 *     description,       // Optional
 *     completed: false,  // Always new
 *     is_public,         // From checkbox
 *     tags,              // From array
 *     created_at: new Date().toISOString(),  // Server time
 *     updated_at: new Date().toISOString()
 *   })
 *   .select()           // Return inserted row
 *   .single()           // Expect exactly one
 * ```
 *
 * ### RLS Security Check
 * Database enforces: `auth.uid() = user_id`
 * - User cannot set user_id to someone else's ID
 * - Database will reject if doesn't match
 * - No way to bypass from client
 *
 * ### Error Handling
 * - RLS violations show as 403 Forbidden
 * - Network errors show timeout
 * - Validation errors show message
 * - All displayed to user in error state
 *
 * ### Success Flow
 * 1. Insert succeeds
 * 2. Clear form fields
 * 3. Call onSuccess callback
 * 4. Parent refetches todos list
 * 5. New todo appears in UI
 *
 * CLOSE: form-submission-handler
 */

/**
 * REF: controlled-input-pattern
 *
 * ## React Controlled Components
 *
 * ### What Are Controlled Components?
 * Input values stored in React state, not DOM
 * - User types → onChange fires → setState → input updates
 * - Single source of truth: state object
 * - Enables real-time validation
 * - Easy to reset or modify values
 *
 * ### Uncontrolled Alternative
 * ```typescript
 * // Uncontrolled - value stored in DOM
 * <input defaultValue="initial" />
 * const value = inputRef.current.value  // Accessed on submit
 * ```
 *
 * ### Controlled Pattern (This File)
 * ```typescript
 * // State holds value
 * const [title, setTitle] = useState('')
 *
 * // Input always reflects state
 * <input
 *   value={title}
 *   onChange={(e) => setTitle(e.target.value)}
 * />
 * ```
 *
 * ### Why Controlled?
 * - Validation as user types
 * - Reset button clears form
 * - Disable during submission
 * - Format/transform input
 * - Prevents invalid states
 *
 * CLOSE: controlled-input-pattern
 */

